/*
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * Builder Xcessory 4.0
 * Code Generator Xcessory 2.0 (09/09/96)
 *
 */
/*
 * Motif required Headers
 */
#include <X11/StringDefs.h>
#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#if (XmVersion >= 1002)
#include <Xm/RepType.h>
#endif
#include <Xm/MwmUtil.h>

/*
 * Globally included information.
 */
#include "defs.h"
#include "w_defs.h"

/*
 * Headers for classes used in this program
 */

/*
 * Common constant and pixmap declarations.
 */
#include "creation-c.h"

/*
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters();
extern XtPointer CONVERT();
extern XtPointer DOUBLE();
extern XtPointer SINGLE();
extern void MENU_POST();
extern Pixmap XPM_PIXMAP();
extern void SET_BACKGROUND_COLOR();

/* Begin user code block <globals> */
/* End user code block <globals> */

/*
 * Change this line via the Output Application Names Dialog.
 */
#define BX_APP_CLASS "BuilderProduct"

int main(argc, argv)
 int argc;
 char **argv;
{
    Widget       parent;
    XtAppContext app;
    Arg          args[256];
    Cardinal     ac;
    Boolean      argok=False;
    Widget   bulletinBoard11;
    Widget   topLevelShell;
    Widget   bulletinBoard;
    
    /* Begin user code block <declarations> */
    /* End user code block <declarations> */
    
    /*
     * The applicationShell is created as an unrealized
     * parent for multiple topLevelShells.  The topLevelShells
     * are created as popup children of the applicationShell.
     * This is a recommendation of Paul Asente & Ralph Swick in
     * _X_Window_System_Toolkit_ p. 677.
     */
    
    parent = XtVaAppInitialize ( &app, BX_APP_CLASS, NULL, 0, 
#ifndef XlibSpecificationRelease
    (Cardinal *) &argc, 
#else
#if (XlibSpecificationRelease>=5)
    &argc, 
#else
    (Cardinal *) &argc, 
#endif
#endif
    argv, NULL, 
    NULL );
    
    RegisterBxConverters(app);
#if (XmVersion >= 1002) 
    XmRepTypeInstallTearOffModelConverter();
#endif
    
    /* Begin user code block <create_shells> */

/******************************************************************************/
/******************************************************************************/

if ( argc == 2 )
if (strcmp("verbose", argv[1]) == 0) verbose = 1;

leggiconf();

/******************************************************************************/
/******************************************************************************/
    /* End user code block <create_shells> */
    
    /*
     * Create classes and widgets used in this program. 
     */
    
    /* Begin user code block <create_topLevelShell3> */
    /* End user code block <create_topLevelShell3> */
    
    bulletinBoard12 = (Widget)CreatebulletinBoard12(parent);
    XtManageChild(bulletinBoard12);
    
    /* Begin user code block <create_xmDialogShell1> */
    /* End user code block <create_xmDialogShell1> */
    
    bulletinBoard13 = (Widget)CreatebulletinBoard13(parent);
    XtManageChild(bulletinBoard13);
    
    /* Begin user code block <create_xmDialogShell> */
    /* End user code block <create_xmDialogShell> */
    
    bulletinBoard11 = (Widget)CreatebulletinBoard11(parent);
    XtManageChild(bulletinBoard11);
    
    /* Begin user code block <create_xmDialogShell2> */
    /* End user code block <create_xmDialogShell2> */
    
    finestraFC = (Widget)CreatefinestraFC(parent);
    
    /* Begin user code block <create_postchopper1> */
    /* End user code block <create_postchopper1> */
    
    finestraFB = (Widget)CreatefinestraFB(parent);
    XtManageChild(finestraFB);
    
    /* Begin user code block <create_dialogShell> */
    /* End user code block <create_dialogShell> */
    
    finestraFA = (Widget)CreatefinestraFA(parent);
    XtManageChild(finestraFA);
    
    /* Begin user code block <create_dialogShell1> */
    /* End user code block <create_dialogShell1> */
    
    finestraFD = (Widget)CreatefinestraFD(parent);
    XtManageChild(finestraFD);
    
    /* Begin user code block <create_topLevelShell1> */
    /* End user code block <create_topLevelShell1> */
    
    finestraFE = (Widget)Createphase_detector(parent);
    XtManageChild(finestraFE);
    
    /* Begin user code block <create_topLevelShell2> */
    /* End user code block <create_topLevelShell2> */
    
    finestraFF = (Widget)CreatefinestraFF(parent);
    XtManageChild(finestraFF);
    
    /* Begin user code block <create_xmDialogShell3> */
    /* End user code block <create_xmDialogShell3> */
    
    finestraFH = (Widget)CreatefinestraFH(parent);
    XtManageChild(finestraFH);
    
    /* Begin user code block <create_xmDialogShell4> */
    /* End user code block <create_xmDialogShell4> */
    
    finestraFG = (Widget)CreatefinestraFG(parent);
    XtManageChild(finestraFG);
    
    /* Begin user code block <create_topLevelShell> */
    /* End user code block <create_topLevelShell> */
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 500); ac++;
    XtSetArg(args[ac], XmNy, 324); ac++;
    XtSetArg(args[ac], XmNwidth, 427); ac++;
    XtSetArg(args[ac], XmNheight, 533); ac++;
    topLevelShell = XtCreatePopupShell("topLevelShell",
        topLevelShellWidgetClass,
        parent,
        args, 
        ac);
    bulletinBoard = (Widget)CreatebulletinBoard(topLevelShell);
    XtManageChild(bulletinBoard);
    XtPopup(XtParent(bulletinBoard), XtGrabNone);
    
    /* Begin user code block <app_procedures> */
    /* End user code block <app_procedures> */
    
    /* Begin user code block <main_loop> */
    /* End user code block <main_loop> */
    
    XtAppMainLoop(app);
    
    /*
     * A return value regardless of whether or not the main loop ends. 
     */
     return(0); 
}
