MAGNET  =       1               
NAME    =       PD1

ALIM1   =       1
N_ALIM1 =       PD1
A_ALIM1 =       1
CU_ALIM1=       160
VO_ALIM1=       30

ALIM2   =       7
N_ALIM2 =       PD2
A_ALIM2 =       7
CU_ALIM2=       160
VO_ALIM2=       30


MAGNET  =       2               
NAME    =       3PQ1

ALIM1   =       2
N_ALIM1 =       3PQ1A
A_ALIM1 =       2
CU_ALIM1=       240
VO_ALIM1=       60

ALIM2   =       3
N_ALIM2 =       3PQ1B
A_ALIM2 =       3
CU_ALIM2=       240
VO_ALIM2=    	60

   
MAGNET  =       3               
NAME    =       1PQ1

ALIM1   =       4
N_ALIM1 =       1PQ1
A_ALIM1 =       4
CU_ALIM1=       160
VO_ALIM1=       30

ALIM2   =       9999
N_ALIM2 =       NULL
A_ALIM2 =       9999
CU_ALIM2=       9999
VO_ALIM2=       9999



MAGNET  =       4               
NAME    =       3PQ2

ALIM1   =       5
N_ALIM1 =       3PQ2A
A_ALIM1 =       5
CU_ALIM1=       240
VO_ALIM1=       60

ALIM2   =       6
N_ALIM2 =       3PQ2B
A_ALIM2 =       6
CU_ALIM2=       240
VO_ALIM2=    	60



MAGNET  =       5               
NAME    =       PD2

ALIM1   =       1
N_ALIM1 =       PD1
A_ALIM1 =       1
CU_ALIM1=       160
VO_ALIM1=       30

ALIM2   =       7
N_ALIM2 =       PD2
A_ALIM2 =       7
CU_ALIM2=       160
VO_ALIM2=       30



MAGNET  =       6               
NAME    =       2PQ1

ALIM1   =       8
N_ALIM1 =       2PQ1A
A_ALIM1 =       8
CU_ALIM1=       160
VO_ALIM1=       33

ALIM2   =       9
N_ALIM2 =       2PQ1B
A_ALIM2 =       9
CU_ALIM2=       160
VO_ALIM2=    	33


MAGNET  =       7               
NAME    =       2PQ2

ALIM1   =       10
N_ALIM1 =       2PQ2A
A_ALIM1 =       10
CU_ALIM1=       160
VO_ALIM1=       33

ALIM2   =       11
N_ALIM2 =       2PQ2B
A_ALIM2 =       11
CU_ALIM2=       160
VO_ALIM2=    	33


MAGNET  =       8               
NAME    =       2PQ3

ALIM1   =       70
N_ALIM1 =       2PQ3A
A_ALIM1 =       70
CU_ALIM1=       160
VO_ALIM1=       33

ALIM2   =       71
N_ALIM2 =       2PQ3B
A_ALIM2 =       71
CU_ALIM2=       160
VO_ALIM2=    	33


MAGNET  =       9               
NAME    =       2PQ4

ALIM1   =       72
N_ALIM1 =       2PQ4A
A_ALIM1 =       72
CU_ALIM1=       200
VO_ALIM1=       30

ALIM2   =       73
N_ALIM2 =       2PQ4B
A_ALIM2 =       73
CU_ALIM2=       200
VO_ALIM2=    	30


BUTTON  =       1
TYPE    =       4
OBJ1    =       9999
OBJ2    =       1
OBJ3    =       9999

BUTTON  =       2
TYPE    =       4
OBJ1    =       9999
OBJ2    =       2
OBJ3    =       9999
OBJ4    =       9999


BUTTON  =       3
TYPE    =       1
OBJ1    =       9999
OBJ2    =       3
OBJ3    =       9999
OBJ4    =       9999

BUTTON  =       4
TYPE    =       4
OBJ1    =       9999
OBJ2    =       4
OBJ3    =       9999
OBJ4    =       9999



BUTTON  =       5
TYPE    =       4
OBJ1    =       9999
OBJ2    =       5
OBJ3    =       9999
OBJ4    =       9999


BUTTON  =       6
TYPE    =       4
OBJ1    =       9999
OBJ2    =       6
OBJ3    =       9999
OBJ4    =       9999


BUTTON  =       7
TYPE    =       4
OBJ1    =       9999
OBJ2    =       7
OBJ3    =       9999
OBJ4    =       9999


BUTTON  =       8
TYPE    =       4
OBJ1    =       9999
OBJ2    =       8
OBJ3    =       9999
OBJ4    =       9999



BUTTON  =       9
TYPE    =       4
OBJ1    =       9999
OBJ2    =       9
OBJ3    =       9999
OBJ4    =       9999



SERVER  =       1
SOCKET  =       3000
HOST    =       192.84.148.4
LINE    =       /dev/tty03
TYPE    =       1
MODE    =       1
VERBOSE =       1
AHOST   =       NONE
ASOCKET =       20000
ALIM    =       1 4 7 8 9 10 11 70 71 72 73 999999 999999 999999 999999 999999
 
SERVER  =       2
SOCKET  =       3001
HOST    =       192.84.148.4
LINE    =       /dev/tty04
TYPE    =       1
MODE    =       1
VERBOSE =       1
AHOST   =       NONE
ASOCKET =       20000
ALIM    =       2 3 5 6 999999 999999 999999 999999 999999 999999 999999 999999 999999 999999 999999 999999
 
