/* inizio SOFTECO */
/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by Builder Xcessory 4.0
 * Generated by Code Generator Xcessory 2.0 (09/09/96)
 *
 */
#ifndef creation_c_H
#define creation_c_H

/*
 * Global widget declarations.
 *        - EXTERNAL is set to extern if the
 *          defs file is not included from the
 *          main file.
 */
#ifdef DECLARE_BX_GLOBALS
#define EXTERNAL
#else
#define EXTERNAL extern
#endif

/*
 * Start Global Widget Declarations.
 */
EXTERNAL Widget   finestraFC;
EXTERNAL Widget   finestraFB;
EXTERNAL Widget   finestraFA;
/*
 * End Global Widget Declarations.
 */
#endif
/* fine SOFTECO */
