/* inizio SOFTECO */
/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * Builder Xcessory 4.0
 * Code Generator Xcessory 2.0 (09/09/96)
 *
 */
#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/MwmUtil.h>
#include <Xm/BulletinB.h>
#include <Xm/ScrollBar.h>
#include <Xm/PushB.h>

/*
 * Global declarations are now stored in the header file.
 *
 * If DECLARE_BX_GLOBALS is defined then this header file
 * declares the globals, otherwise it just externs them.
 */
#define DECLARE_BX_GLOBALS

/*
 * Globally included information.
 */


/*
 * Common constant and pixmap declarations.
 */
#include "creation-c.h"

/*
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters();
extern XtPointer CONVERT();
extern XtPointer DOUBLE();
extern XtPointer SINGLE();
extern void MENU_POST();
extern Pixmap XPM_PIXMAP();
extern void SET_BACKGROUND_COLOR();

/*
 * Declarations for callbacks and handlers.
 */
void BxExitCB();
void AttivaFinestra();

/*
 * Create the finestraFC hierarchy of widgets.
 */
Widget
CreatefinestraFC(parent)
Widget parent;
{
    Arg      args[256];
    Cardinal ac=0;
    Cardinal cdc=0;
    Boolean  argok=False;
    Widget   XmDialogShell2;
    Widget   scrollBar1;
    Widget   pushButton7;
    Widget   pushButton8;
    
    /*
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent)); 
    XtInitializeWidgetClass(xmDialogShellWidgetClass);
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmScrollBarWidgetClass);
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 174); ac++;
    XtSetArg(args[ac], XmNy, 156); ac++;
    XtSetArg(args[ac], XmNwidth, 309); ac++;
    XtSetArg(args[ac], XmNheight, 156); ac++;
    XmDialogShell2 = XtCreatePopupShell("XmDialogShell2",
        xmDialogShellWidgetClass,
        parent,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNdialogTitle, 
        CONVERT(parent, "FC", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 174); ac++;
    XtSetArg(args[ac], XmNy, 156); ac++;
    finestraFC = XmCreateBulletinBoard(XmDialogShell2,
        "finestraFC",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNx, 100); ac++;
    XtSetArg(args[ac], XmNy, 120); ac++;
    scrollBar1 = XmCreateScrollBar(finestraFC,
        "scrollBar1",
        args, 
        ac);
    XtManageChild(scrollBar1);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "I", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 240); ac++;
    XtSetArg(args[ac], XmNy, 50); ac++;
    XtSetArg(args[ac], XmNwidth, 40); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    pushButton7 = XmCreatePushButton(finestraFC,
        "pushButton7",
        args, 
        ac);
    XtManageChild(pushButton7);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "H", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 20); ac++;
    XtSetArg(args[ac], XmNy, 80); ac++;
    XtSetArg(args[ac], XmNwidth, 40); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    pushButton8 = XmCreatePushButton(finestraFC,
        "pushButton8",
        args, 
        ac);
    XtManageChild(pushButton8);
    
    
    /* Begin user code block <end_CreatefinestraFC> */
    /* End user code block <end_CreatefinestraFC> */
    return( finestraFC );
}

/*
 * Create the finestraFB hierarchy of widgets.
 */
Widget
CreatefinestraFB(parent)
Widget parent;
{
    Arg      args[256];
    Cardinal ac=0;
    Cardinal cdc=0;
    Boolean  argok=False;
    Widget   XmDialogShell1;
    Widget   scrollBar;
    Widget   pushButton6;
    Widget   pushButton5;
    
    /*
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent)); 
    XtInitializeWidgetClass(xmDialogShellWidgetClass);
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmScrollBarWidgetClass);
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 159); ac++;
    XtSetArg(args[ac], XmNy, 403); ac++;
    XtSetArg(args[ac], XmNwidth, 350); ac++;
    XtSetArg(args[ac], XmNheight, 210); ac++;
    XmDialogShell1 = XtCreatePopupShell("XmDialogShell1",
        xmDialogShellWidgetClass,
        parent,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNdialogTitle, 
        CONVERT(parent, "FB", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 159); ac++;
    XtSetArg(args[ac], XmNy, 403); ac++;
    finestraFB = XmCreateBulletinBoard(XmDialogShell1,
        "finestraFB",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNx, 100); ac++;
    XtSetArg(args[ac], XmNy, 120); ac++;
    scrollBar = XmCreateScrollBar(finestraFB,
        "scrollBar",
        args, 
        ac);
    XtManageChild(scrollBar);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 220); ac++;
    XtSetArg(args[ac], XmNy, 120); ac++;
    pushButton6 = XmCreatePushButton(finestraFB,
        "pushButton6",
        args, 
        ac);
    XtManageChild(pushButton6);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 120); ac++;
    pushButton5 = XmCreatePushButton(finestraFB,
        "pushButton5",
        args, 
        ac);
    XtManageChild(pushButton5);
    
    
    /* Begin user code block <end_CreatefinestraFB> */
    /* End user code block <end_CreatefinestraFB> */
    return( finestraFB );
}

/*
 * Create the finestraFA hierarchy of widgets.
 */
Widget
CreatefinestraFA(parent)
Widget parent;
{
    Arg      args[256];
    Cardinal ac=0;
    Cardinal cdc=0;
    Boolean  argok=False;
    Widget   dialogShell;
    Widget   pushButton4;
    Widget   pushButton3;
    
    /*
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent)); 
    XtInitializeWidgetClass(xmDialogShellWidgetClass);
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 226); ac++;
    XtSetArg(args[ac], XmNy, 208); ac++;
    XtSetArg(args[ac], XmNwidth, 306); ac++;
    XtSetArg(args[ac], XmNheight, 181); ac++;
    dialogShell = XtCreatePopupShell("dialogShell",
        xmDialogShellWidgetClass,
        parent,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNdialogTitle, 
        CONVERT(parent, "FA", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 226); ac++;
    XtSetArg(args[ac], XmNy, 208); ac++;
    XtSetArg(args[ac], XmNwidth, 306); ac++;
    XtSetArg(args[ac], XmNheight, 181); ac++;
    finestraFA = XmCreateBulletinBoard(dialogShell,
        "finestraFA",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "E", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 180); ac++;
    XtSetArg(args[ac], XmNy, 80); ac++;
    XtSetArg(args[ac], XmNwidth, 79); ac++;
    XtSetArg(args[ac], XmNheight, 44); ac++;
    pushButton4 = XmCreatePushButton(finestraFA,
        "pushButton4",
        args, 
        ac);
    XtManageChild(pushButton4);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "D", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 50); ac++;
    XtSetArg(args[ac], XmNy, 80); ac++;
    XtSetArg(args[ac], XmNwidth, 79); ac++;
    XtSetArg(args[ac], XmNheight, 44); ac++;
    pushButton3 = XmCreatePushButton(finestraFA,
        "pushButton3",
        args, 
        ac);
    XtManageChild(pushButton3);
    
    
    /* Begin user code block <end_CreatefinestraFA> */
    /* End user code block <end_CreatefinestraFA> */
    return( finestraFA );
}

/*
 * Create the bulletinBoard hierarchy of widgets.
 */
Widget
CreatebulletinBoard(parent)
Widget parent;
{
    Arg      args[256];
    Cardinal ac=0;
    Cardinal cdc=0;
    Boolean  argok=False;
    Widget   bulletinBoard;
    Widget   pushButton9;
    Widget   pushButton2;
    Widget   pushButton1;
    Widget   pushButton;
    
    /*
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent)); 
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 531); ac++;
    XtSetArg(args[ac], XmNy, 45); ac++;
    XtSetArg(args[ac], XmNwidth, 439); ac++;
    XtSetArg(args[ac], XmNheight, 180); ac++;
    bulletinBoard = XmCreateBulletinBoard(parent,
        "bulletinBoard",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Quit", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 20); ac++;
    XtSetArg(args[ac], XmNy, 20); ac++;
    XtSetArg(args[ac], XmNwidth, 104); ac++;
    XtSetArg(args[ac], XmNheight, 50); ac++;
    pushButton9 = XmCreatePushButton(bulletinBoard,
        "pushButton9",
        args, 
        ac);
    XtManageChild(pushButton9);
    XtAddCallback(pushButton9, XmNactivateCallback, BxExitCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "C", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 270); ac++;
    XtSetArg(args[ac], XmNy, 100); ac++;
    XtSetArg(args[ac], XmNwidth, 107); ac++;
    XtSetArg(args[ac], XmNheight, 38); ac++;
    pushButton2 = XmCreatePushButton(bulletinBoard,
        "pushButton2",
        args, 
        ac);
    XtManageChild(pushButton2);
    XtAddCallback(pushButton2, XmNactivateCallback, AttivaFinestra, (XtPointer)"C");
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "B\r", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 160); ac++;
    XtSetArg(args[ac], XmNy, 100); ac++;
    XtSetArg(args[ac], XmNwidth, 107); ac++;
    XtSetArg(args[ac], XmNheight, 38); ac++;
    pushButton1 = XmCreatePushButton(bulletinBoard,
        "pushButton1",
        args, 
        ac);
    XtManageChild(pushButton1);
    XtAddCallback(pushButton1, XmNactivateCallback, AttivaFinestra, (XtPointer)"B");
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "A", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 30); ac++;
    XtSetArg(args[ac], XmNy, 100); ac++;
    XtSetArg(args[ac], XmNwidth, 107); ac++;
    XtSetArg(args[ac], XmNheight, 38); ac++;
    pushButton = XmCreatePushButton(bulletinBoard,
        "pushButton",
        args, 
        ac);
    XtManageChild(pushButton);
    XtAddCallback(pushButton, XmNactivateCallback, AttivaFinestra, (XtPointer)"A");
    
    
    /* Begin user code block <end_CreatebulletinBoard> */
    /* End user code block <end_CreatebulletinBoard> */
    return( bulletinBoard );
}
/* fine SOFTECO */
