# /etc/nslink.conf --- configuration file for NS-Link driver

bootfile	/etc/rpshsi.bin
bootfile-2p     /etc/rpshsi2p.bin
bootfile-DM     /etc/devmast.bin

# Ethernet address   interface   number of ports (2/4/8)    link timeout (sec)

00:C0:4E:06:00:05    eth0        4                          600

# Port number (1-8)   RsMode (232, 422, 485, 485_2-wire, 485_4-wire_master, 485_4-wire_slave, or Off)
1                     485
2                     485
3                     Off
4                     Off

# IP address         number of ports (2/4/8)   link timeout (sec)

192.168.19.74        8                         10

# Port number (1-8)   RsMode (232, 422, 485, 485_2-wire, 485_4-wire_master, 485_4-wire_slave, or Off)
1                     232
2                     232
3                     232
4                     232
5                     232
6                     232
7                     232
8                     232
